name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
    
jobs:
  consistency-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set up Go 1.25
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
          go-version: 1.25.x

    - name: OS details
      run: |
          uname -a
          if [ -e /etc/os-release ]; then cat /etc/os-release; fi

    - name: Code format check
      run: ./.github/scripts/gofmt

    - name: golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: latest

  basic-tests:
    name: Basic tests
    timeout-minutes: 60
    needs: consistency-checks
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        go-version: ['1.24.x', '1.25.x' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
  
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: OS details
        run: |
            echo This is Github OS ${{ runner.os }}
            uname -a
            if [ -e /etc/os-release ]; then cat /etc/os-release; fi

      - name: Install Ubuntu upackages
        if: ${{ runner.os == 'Linux'}}
        run: |
              sudo apt-get install -y krb5-user libkrb5-dev pkg-config

      - name: Generate test includes
        run: |
          echo pkgs=$(go list ./... | egrep -v '/examples/|/build-tools/') >> "$GITHUB_ENV"

      - name: Run tests
        run: |
          go test $pkgs -count 100 -coverprofile=cover.out -covermode=atomic
          pushd http/test
          go test -coverpkg ../ -coverprofile=cover.out -covermode=atomic
          popd
          go run github.com/wadey/gocovmerge@latest ./cover.out ./http/test/cover.out > cover-all.out

      - name: Check test coverage
        if: ${{ runner.os == 'Linux' && matrix.go-version == '1.25.x'  }}
        uses: jake-scott/go-test-coverage@645a68c404cf3e70edf5a8d9ce4ca7ab7eb1b483 # v1.0.0
        with:
          config: ./.testcoverage.yml
